import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadAgents, loadSkills, loadTaxonomy } from "../lib/registry.ts";
import { CATALOG_DIR } from "../lib/paths.ts";
import { c, error, info, ok } from "../lib/log.ts";
import type { AgentRecord, SkillRecord, Taxonomy } from "../types.ts";

function byName(a: { name: string }, b: { name: string }): number {
  return a.name.localeCompare(b.name);
}

function buildIndex(taxonomy: Taxonomy, agents: AgentRecord[], skills: SkillRecord[]): string {
  const index = {
    schema: "claudemax/catalog@1",
    taxonomyVersion: taxonomy.version,
    counts: {
      agents: agents.length,
      skills: skills.length,
      categories: taxonomy.categories.length,
    },
    agents: [...agents].sort(byName).map((a) => ({
      name: a.name,
      description: a.description,
      category: a.category,
      model: a.model,
      tools: a.tools,
      tags: a.tags,
      skills: a.skills,
      version: a.version,
      status: a.status,
      path: a.relPath,
    })),
    skills: [...skills].sort(byName).map((s) => ({
      name: s.name,
      description: s.description,
      category: s.category,
      tags: s.tags,
      version: s.version,
      status: s.status,
      path: s.relPath,
    })),
  };
  return `${JSON.stringify(index, null, 2)}\n`;
}

function statusBadge(status: string): string {
  if (status === "experimental") return " 🧪";
  if (status === "deprecated") return " ⚠️";
  return "";
}

function buildMarkdown(taxonomy: Taxonomy, agents: AgentRecord[], skills: SkillRecord[]): string {
  const lines: string[] = [];
  lines.push("# ClaudeMax Catalog");
  lines.push("");
  lines.push("> Generated by `cmx catalog`. Do not edit by hand — run `npm run catalog` to regenerate.");
  lines.push("");
  lines.push(`**${agents.length}** agents · **${skills.length}** skills · **${taxonomy.categories.length}** categories · taxonomy v${taxonomy.version}`);
  lines.push("");
  lines.push("Legend: 🧪 experimental · ⚠️ deprecated");
  lines.push("");

  // Counts table.
  lines.push("## Overview");
  lines.push("");
  lines.push("| Category | Agents | Skills |");
  lines.push("| --- | --: | --: |");
  for (const cat of taxonomy.categories) {
    const a = agents.filter((x) => x.category === cat.id).length;
    const s = skills.filter((x) => x.category === cat.id).length;
    if (a === 0 && s === 0) continue;
    lines.push(`| [${cat.title}](#${cat.id}) | ${a} | ${s} |`);
  }
  lines.push("");

  for (const cat of taxonomy.categories) {
    const catAgents = agents.filter((x) => x.category === cat.id).sort(byName);
    const catSkills = skills.filter((x) => x.category === cat.id).sort(byName);
    if (catAgents.length === 0 && catSkills.length === 0) continue;

    lines.push(`## ${cat.title}`);
    lines.push("");
    lines.push(`<a id="${cat.id}"></a>${cat.summary}`);
    lines.push("");

    if (catAgents.length) {
      lines.push("### Agents");
      lines.push("");
      lines.push("| Agent | Model | Description | Skills |");
      lines.push("| --- | --- | --- | --- |");
      for (const a of catAgents) {
        const deps = a.skills.length ? a.skills.map((d) => `\`${d}\``).join(", ") : "—";
        lines.push(`| [\`${a.name}\`](../${a.relPath})${statusBadge(a.status)} | ${a.model ?? "inherit"} | ${escapeCell(a.description)} | ${deps} |`);
      }
      lines.push("");
    }

    if (catSkills.length) {
      lines.push("### Skills");
      lines.push("");
      lines.push("| Skill | Description |");
      lines.push("| --- | --- |");
      for (const s of catSkills) {
        lines.push(`| [\`${s.name}\`](../${s.relPath})${statusBadge(s.status)} | ${escapeCell(s.description)} |`);
      }
      lines.push("");
    }
  }

  return `${lines.join("\n")}\n`;
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ").trim();
}

export function runCatalog(argv: string[]): number {
  const check = argv.includes("--check");
  const taxonomy = loadTaxonomy();
  const agents = loadAgents();
  const skills = loadSkills();

  const indexContent = buildIndex(taxonomy, agents, skills);
  const mdContent = buildMarkdown(taxonomy, agents, skills);

  const indexPath = join(CATALOG_DIR, "index.json");
  const mdPath = join(CATALOG_DIR, "CATALOG.md");

  if (check) {
    const current = (p: string) => (existsSync(p) ? readFileSync(p, "utf8") : "");
    const stale: string[] = [];
    if (current(indexPath) !== indexContent) stale.push("catalog/index.json");
    if (current(mdPath) !== mdContent) stale.push("catalog/CATALOG.md");
    if (stale.length) {
      error(`Catalog is out of date: ${stale.join(", ")}. Run ${c.cyan("npm run catalog")} and commit the result.`);
      return 1;
    }
    ok("Catalog is up to date.");
    return 0;
  }

  mkdirSync(CATALOG_DIR, { recursive: true });
  writeFileSync(indexPath, indexContent, "utf8");
  writeFileSync(mdPath, mdContent, "utf8");
  ok(`Wrote catalog/index.json and catalog/CATALOG.md (${agents.length} agents, ${skills.length} skills).`);
  info("");
  return 0;
}
